name: Clean workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.terpconnect.umd.edu }}
          username: ${{ secrets.kchong5463 }}
          password: ${{ secrets.testing123 }}
          port: ${{ secrets.22 }}
          script: |
            unalias rm
            rm -rf <Repo-Name>